
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build1:

    runs-on: ubuntu-latest #creating a server to run the jobs

    steps:
    - uses: actions/checkout@v4  #cloning current repository into server e.g gitclone
    - name: Set up Python 3.10  
      uses: actions/setup-python@v3  #installing python on server

    - name: Install dependencies 
      run: |
        sudo apt install python3-pip python3-venv -y
        python3 -m venv venv_game
        source venv_game/bin/activate
        pip install streamlit
        # streamlit run play_game.py
        
    - name: check server ip 
      run: |
        echo $(hostname -i)
      

  build2:

    runs-on: ubuntu-latest #creating a server to run the jobs

    steps:
    - uses: actions/checkout@v4  #cloning current repository into server e.g gitclone
    - name: Set up Python 3.10  
      uses: actions/setup-python@v3  #installing python on server

        
    - name: check server ip 
      run: |
        echo $(hostname -i)
      
  
